
services:
  app:
    build: .
    container_name: electronics_web
    volumes:
      - .:/electronics_app
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - electronics_net


  db:
    image: mysql:8.0
    container_name: electronics_db
    restart: always
    env_file:
      - .docker.env
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - electronics_net


networks:
  electronics_net:

volumes:
  mysql_data:
